"""create portfolio stock and holding tables

Revision ID: 31d018bc8d68
Revises: 74c3873fb501
Create Date: 2026-08-03 03:08:58.183148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d018bc8d68'
down_revision: Union[str, Sequence[str], None] = '74c3873fb501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.add_column('holdings', sa.Column('stock_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_holdings_ticker'), table_name='holdings')
    op.create_foreign_key(None, 'holdings', 'stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.drop_column('holdings', 'sector')
    op.drop_column('holdings', 'company_name')
    op.drop_column('holdings', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('holdings', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('holdings', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.create_index(op.f('ix_holdings_ticker'), 'holdings', ['ticker'], unique=False)
    op.drop_column('holdings', 'stock_id')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
