import { useEffect, useRef, useState } from 'react'
import { Bot, ChevronRight, FileText, MessageSquarePlus, Send, Sparkles, Trash2, UserRound } from 'lucide-react'
import { ErrorState, LoadingBlock } from '../components/common/Feedback'
import { usePortfolio } from '../hooks/usePortfolio'
import { getApiError } from '../services/api'
import { chatService } from '../services/chatService'
import type { ChatMessage, ChatSource, Conversation } from '../types'

export default function Copilot() {
  const { activePortfolio } = usePortfolio(); const [conversations, setConversations] = useState<Conversation[]>([]); const [conversationId, setConversationId] = useState<number | undefined>(); const [messages, setMessages] = useState<ChatMessage[]>([]); const [sources, setSources] = useState<ChatSource[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const scrollRef = useRef<HTMLDivElement>(null)
  const loadConversations = async () => { try { setConversations(await chatService.conversations()) } catch (err) { setError(getApiError(err, 'Unable to load conversations.')) } }
  useEffect(() => { loadConversations().finally(() => setLoading(false)) }, [])
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }) }, [messages, sending])
  const openConversation = async (id: number) => { setLoading(true); setError(''); try { const item = await chatService.conversation(id); setConversationId(id); setMessages(item.messages); setSources([]) } catch (err) { setError(getApiError(err)) } finally { setLoading(false) } }
  const newConversation = () => { setConversationId(undefined); setMessages([]); setSources([]); setError('') }
  const ask = async (event: React.FormEvent) => { event.preventDefault(); const prompt = input.trim(); if (!prompt || sending) return; setInput(''); setMessages((current) => [...current, { role: 'user', content: prompt }]); setSending(true); setError(''); try { const response = await chatService.ask({ message: prompt, portfolio_id: activePortfolio?.id, conversation_id: conversationId }); setConversationId(response.conversation_id); setMessages((current) => [...current, { role: 'assistant', content: response.message }]); setSources(response.sources); await loadConversations() } catch (err) { setMessages((current) => current.slice(0, -1)); setError(getApiError(err, 'FinGenie could not answer that right now.')) } finally { setSending(false) } }
  const removeConversation = async (event: React.MouseEvent, id: number) => { event.stopPropagation(); try { await chatService.remove(id); if (id === conversationId) newConversation(); await loadConversations() } catch (err) { setError(getApiError(err)) } }
  if (loading && conversations.length === 0) return <LoadingBlock label="Loading AI Copilot…" />
  return <div className="copilot-layout"><aside className="conversation-list"><button className="new-chat" onClick={newConversation}><MessageSquarePlus size={17} />New conversation</button><p className="sidebar-label">RECENT CONVERSATIONS</p>{conversations.length ? conversations.map((item) => <button key={item.id} onClick={() => void openConversation(item.id)} className={`conversation-item ${item.id === conversationId ? 'selected' : ''}`}><span>{item.title || 'Untitled conversation'}</span><Trash2 size={14} onClick={(event) => void removeConversation(event, item.id)} /></button>) : <p className="conversation-empty">Your conversations will appear here.</p>}</aside><section className="chat-panel"><div className="chat-header"><div className="copilot-symbol"><Sparkles size={18} /></div><div><h2>FinGenie AI Copilot</h2><p>{activePortfolio ? `Connected to ${activePortfolio.name}` : 'General financial knowledge'}</p></div></div>{error && <ErrorState message={error} />}<div className="message-area" ref={scrollRef}>{messages.length === 0 ? <div className="chat-welcome"><div className="chat-welcome-mark"><Bot size={27} /></div><h3>What would you like to know?</h3><p>I can explain your portfolio data, look up market information, analyze sector allocation, and answer questions from uploaded financial documents.</p><div className="suggestion-grid"><button onClick={() => setInput('What is my portfolio summary?')}>What is my portfolio summary?<ChevronRight size={15} /></button><button onClick={() => setInput('How is my portfolio allocated by sector?')}>How is my portfolio allocated by sector?<ChevronRight size={15} /></button><button onClick={() => setInput('What is the current price of TCS?')}>What is the current price of TCS?<ChevronRight size={15} /></button></div></div> : messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}><span className="message-avatar">{message.role === 'assistant' ? <Bot size={16} /> : <UserRound size={16} />}</span><div>{message.content}</div></div>)}{sending && <div className="message assistant"><span className="message-avatar"><Bot size={16} /></span><div className="typing"><i /><i /><i /></div></div>}</div>{sources.length > 0 && <div className="source-strip"><FileText size={16} /><span>Sources:</span>{sources.map((source) => <span className="source-pill" key={`${source.source}-${source.chunk_index}`}>{source.source} · Chunk {source.chunk_index}</span>)}</div>}<form className="chat-input" onSubmit={ask}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about your portfolio, markets, or documents…" maxLength={2000} /><button className="button icon-send" disabled={!input.trim() || sending} aria-label="Send message"><Send size={18} /></button></form></section></div>
}
