import { useEffect, useState } from 'react'
import { ArrowUpRight, BriefcaseBusiness, CircleDollarSign, Landmark, Plus, Sparkles, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import AllocationChart from '../components/charts/AllocationChart'
import { EmptyState, ErrorState, LoadingBlock } from '../components/common/Feedback'
import { useAuth } from '../hooks/useAuth'
import { usePortfolio } from '../hooks/usePortfolio'
import { getApiError } from '../services/api'
import { portfolioService } from '../services/portfolioService'
import type { PortfolioSummary, SectorAllocation } from '../types'

const rupees = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value)

export default function Dashboard() {
  const { user } = useAuth(); const { activePortfolio } = usePortfolio()
  const [summary, setSummary] = useState<PortfolioSummary | null>(null); const [allocation, setAllocation] = useState<SectorAllocation[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!activePortfolio) { setSummary(null); setAllocation([]); return }; setLoading(true); setError(''); Promise.all([portfolioService.summary(activePortfolio.id), portfolioService.allocation(activePortfolio.id)]).then(([nextSummary, nextAllocation]) => { setSummary(nextSummary); setAllocation(nextAllocation) }).catch((err) => setError(getApiError(err, 'Unable to load this portfolio.'))).finally(() => setLoading(false)) }, [activePortfolio?.id])
  const firstName = user?.full_name.split(' ')[0] ?? 'there'
  if (!activePortfolio) return <EmptyState icon={<BriefcaseBusiness size={32} />} title="Start with your first portfolio" text="Create a portfolio, then add your investments to unlock FinGenie analytics." action={<Link className="button" to="/portfolio"><Plus size={17} />Create portfolio</Link>} />
  if (loading) return <LoadingBlock />
  if (error) return <ErrorState message={error} />
  const positive = (summary?.profit_loss ?? 0) >= 0
  return <div className="dashboard"><section className="welcome-row"><div><p className="eyebrow">{activePortfolio.name.toUpperCase()} · {activePortfolio.base_currency}</p><h2>Good to see you, {firstName}.</h2><p className="muted">A clear view of your investments, powered by live market data.</p></div><Link className="button" to="/portfolio"><Plus size={17} />Add holding</Link></section><section className="metric-grid"><article className="metric-card"><span className="metric-icon teal"><WalletCards size={20} /></span><span>Current value</span><strong>{rupees(summary?.current_value ?? 0)}</strong><small>Live market valuation</small></article><article className="metric-card"><span className="metric-icon blue"><Landmark size={20} /></span><span>Total invested</span><strong>{rupees(summary?.total_investment ?? 0)}</strong><small>{summary?.holding_count ?? 0} holdings tracked</small></article><article className="metric-card"><span className={`metric-icon ${positive ? 'green' : 'red'}`}><CircleDollarSign size={20} /></span><span>Overall return</span><strong className={positive ? 'positive' : 'negative'}>{positive ? '+' : ''}{rupees(summary?.profit_loss ?? 0)}</strong><small className={positive ? 'positive' : 'negative'}>{positive ? '+' : ''}{summary?.return_percentage ?? 0}% since purchase</small></article></section><section className="dashboard-grid"><article className="panel allocation-panel"><div className="panel-head"><div><p className="eyebrow">ALLOCATION</p><h3>Sector exposure</h3></div><Link to="/analytics" className="text-link">Explore <ArrowUpRight size={15} /></Link></div><AllocationChart data={allocation} /><div className="allocation-legend">{allocation.slice(0, 4).map((item, index) => <div key={item.sector}><span className={`legend-dot dot-${index}`} />{item.sector}<strong>{item.percentage.toFixed(1)}%</strong></div>)}</div></article><article className="panel insight-panel"><div className="panel-head"><div><p className="eyebrow">FIN GENIE AI</p><h3>Understand your portfolio</h3></div><Sparkles className="sparkle" size={22} /></div><p>Ask about your returns, sector allocation, stock prices, or financial documents in one conversation.</p><div className="prompt-stack"><Link to="/copilot">“How diversified is my portfolio?” <ArrowUpRight size={15} /></Link><Link to="/copilot">“Explain my current returns.” <ArrowUpRight size={15} /></Link></div><Link className="button dark" to="/copilot">Open AI Copilot</Link></article></section><section className="panel next-step"><div><span className="metric-icon purple"><Sparkles size={19} /></span><div><h3>Bring your research into the conversation</h3><p className="muted">Upload SEBI circulars, reports, or reference documents and ask FinGenie questions grounded in them.</p></div></div><Link className="text-link" to="/documents">Open knowledge base <ArrowUpRight size={15} /></Link></section></div>
}
