import { useRef, useState } from 'react'
import { CheckCircle2, FileUp, ShieldCheck, UploadCloud } from 'lucide-react'
import { ErrorState } from '../components/common/Feedback'
import { getApiError } from '../services/api'
import { documentService } from '../services/documentService'

export default function Documents() {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const upload = async () => { if (!file) return; setError(''); setSuccess(''); setUploading(true); try { await documentService.upload(file); setSuccess(`${file.name} was added to FinGenie's knowledge base.`); setFile(null); if (inputRef.current) inputRef.current.value = '' } catch (err) { setError(getApiError(err, 'Unable to upload this document.')) } finally { setUploading(false) } }
  return <div className="documents-page"><section className="page-heading"><div><p className="eyebrow">RAG KNOWLEDGE BASE</p><h2>Ground your questions in documents</h2><p className="muted">Add financial PDFs, then ask the AI Copilot questions with source citations.</p></div></section><section className="upload-panel"><div className="upload-icon"><UploadCloud size={28} /></div><h3>Upload a financial document</h3><p>FinGenie currently accepts PDF files and securely ingests their content for retrieval.</p><input ref={inputRef} type="file" accept="application/pdf,.pdf" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setSuccess(''); setError('') }} />{file ? <div className="file-selected"><FileUp size={19} /><span>{file.name}</span><small>{(file.size / 1024 / 1024).toFixed(2)} MB</small><button className="button" onClick={() => void upload()} disabled={uploading}>{uploading ? 'Uploading…' : 'Add to knowledge base'}</button></div> : <button className="button secondary" onClick={() => inputRef.current?.click()}><FileUp size={17} />Choose a PDF</button>}{error && <ErrorState message={error} />}{success && <p className="success-message"><CheckCircle2 size={18} />{success}</p>}</section><section className="document-note"><ShieldCheck size={22} /><div><h3>How it works</h3><p>When you ask a document-related question, FinGenie retrieves relevant passages from the indexed PDFs and shows the source file and chunk in the response.</p></div></section></div>
}
